version: '3.9'

services:

  web_app:
    build: .
    volumes:
      - .:/usr/src/app/volumes/web/
    ports:
      - "8081:8081"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - .:/usr/src/app/volumes/postgresql/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file:
      - ./.env.dev
