version: '3.9'

services:

  web_app:
    build: .
    volumes:
      - .:/usr/src/app/volumes/web/
    ports:
      - "8081:8081"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - .:/usr/src/app/volumes/postgresql/
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    env_file:
      - ./.env.dev
