# Generated by Django 3.1.5 on 2021-02-10 13:13

from django.db import migrations, models
import trade_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reserved_balance',
            field=models.FloatField(default=0, validators=[trade_app.validators.validate_price]),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reserved_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
