# Generated by Django 3.1.5 on 2021-02-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='items',
        ),
    ]
