# Generated by Django 3.1.5 on 2021-02-09 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0007_auto_20210209_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='item',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='price',
        ),
    ]
